### PR TITLE
Topic dataset collection task

### PR DESCRIPTION
**Pull request by nzinci**
Hi. Everything in "Topic dataset collection" dir. 
Work Pipeline in Pipeline.md file. 
Dataset is in negative_tweets.txt.zip file

### CODE REVIEW

**Comment by nzinci** [comment]
Hi @Lavriz can I ask for the review please

**Comment by evgenydmitriev** [comment]
@nzinci thanks for your submission. Unfortunately, your data and corresponding scripts don't meet the requirements of the challenge. Specifically, using keywords or their synonyms introduces bias in the datasets and affects later stages of building models.

**Comment by nzinci** [comment]
Yeah, as I mentioned in description I was in the time limits. So can I tune
my solution during the weekends, please?

**Comment by evgenydmitriev** [comment]
Sure, just keep the bigger picture in mind.

**Pull request closed without merging**
